INSERT INTO states (id, name, created_at, updated_at, deleted_at)
VALUES (1, 'Buenos Aires', NOW(), NOW(), NULL),
       (2, 'Capital Federal', NOW(), NOW(), NULL),
       (3, 'Catamarca', NOW(), NOW(), NULL),
       (4, 'Chaco', NOW(), NOW(), NULL),
       (5, 'Chubut', NOW(), NOW(), NULL),
       (6, 'Cordoba', NOW(), NOW(), NULL),
       (7, 'Corrientes', NOW(), NOW(), NULL),
       (8, 'Entre Rios', NOW(), NOW(), NULL),
       (9, 'Formosa', NOW(), NOW(), NULL),
       (10, 'Jujuy', NOW(), NOW(), NULL),
       (11, 'La Pampa', NOW(), NOW(), NULL),
       (12, 'La Rioja', NOW(), NOW(), NULL),
       (13, 'Mendoza', NOW(), NOW(), NULL),
       (14, 'Misiones', NOW(), NOW(), NULL),
       (15, 'Neuquen', NOW(), NOW(), NULL),
       (16, 'Rio Negro', NOW(), NOW(), NULL),
       (17, 'Salta', NOW(), NOW(), NULL),
       (18, 'San Juan', NOW(), NOW(), NULL),
       (19, 'San Luis', NOW(), NOW(), NULL),
       (20, 'Santa Cruz', NOW(), NOW(), NULL),
       (21, 'Santa Fe', NOW(), NOW(), NULL),
       (22, 'Santiago del Estero', NOW(), NOW(), NULL),
       (23, 'Tierra del Fuego', NOW(), NOW(), NULL),
       (24, 'Tucuman', NOW(), NOW(), NULL);

